export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const CLEAR_STATE = 'CLEAR_STATE';
export const SET_IS_FETCHING_DATA = 'SET_IS_FETCHING_DATA';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_PICTURE_RESPONSE = 'SET_PICTURE_RESPONSE';